### PR TITLE
Upgrade CLDR data to v40, fix British subdivision localizations

### PR DESCRIPTION
**Pull request by mlocati**
See https://github.com/punic/data/pull/17 and https://github.com/punic/data/pull/18

### CODE REVIEW

**Comment by mlocati** [comment]
@c960657 what about the commit https://github.com/punic/punic/pull/414/commits/af3f04ae679ab0731f7b58db4d1d95033709bafc included in this PR? Does it look good to you?

**Comment by c960657** [comment]
> @c960657 what about the commit [af3f04a](https://github.com/punic/punic/commit/af3f04ae679ab0731f7b58db4d1d95033709bafc) included in this PR? Does it look good to you?

Is en_CN an official locale? I don't see it on https://github.com/unicode-org/cldr/tree/main/common/main.

**Comment by mlocati** [comment]
> Is en_CN an official locale?

Nope. That's why it's here IIRC: Punic also supports "strange" combinations of languages and countries, falling back to the most similar official locale.
I was wondering if the skeleton formats look ok to you (I think the fallback is en_001)

**Comment by c960657** [comment]
Oh, yes, looks right AFAICT :-)

**Pull request merged**
