### PR TITLE
Use isset instead of array_key_exists

### PR DESCRIPTION
**Pull request by LukasReschke**
O(n) vs O(1)

Ref https://github.com/owncloud/core/issues/13434

### CODE REVIEW

**Comment by LukasReschke** [comment]
This gives about 300ms for 100'000 invocations.

**Comment by Remo** [comment]
is this about `Punic\Calendar::formatDatetime` or do you have any other performance issues at the moment? Might be helpful to have a benchmark script in the repo to run such tests. Performance was never an issue in my projects but I hardly ever have more than 10 punic calls per request..

**Comment by Remo** [comment]
@LukasReschke I'm trying to collect things we can improve over here, maybe you have some ideas / suggestions too https://github.com/punic/punic/issues/32

**Comment by mlocati** [comment]
> O(n) vs O(1)

PS: @LukasReschke: Isn't `$array[$key]` an O(n) ?

**Comment by LukasReschke** [comment]
> is this about Punic\Calendar::formatDatetime or do you have any other performance issues at the moment? 

That's what we use at the moment – yes. My main concern is that a simple conversion of about 20k dates takes multiple seconds, for our use-case this is very undesirable.

>  Isn't $array[$key] an O(n) ?

Generally speaking `$foo[$key]` is a direct key access which is O(1), you can btw. also use it on strings to determine it's length, instead of counting the length, this makes a considerable difference as well especially with longer strings. Furthermore `isset()` is a language construct and so way faster if called multiple times than other non-language construct equivalents.

**Comment by stof** [comment]
2 things here:

- both code are not equivalent (``isset`` returns false if the key exists but contains a ``null`` value), so changes must be evaluated carefully (it is safe in many places, but not always)
- are you profiling with XDebug enabled ? XDebug is known to slow down the function calls a lot. the difference between array_key_exists and isset is much bigger with XDebug than without it (which is also why XDebug should never be enabled on prod servers)

**Comment by LukasReschke** [comment]
> are you profiling with XDebug enabled ? XDebug is known to slow down the function calls a lot. the difference between array_key_exists and isset is much bigger with XDebug than without it (which is also why XDebug should never be enabled on prod servers)

XDebug is disabled on my local machine ;-)

**Comment by mlocati** [comment]
> both code are not equivalent (isset returns false if the key exists but contains a null value), so changes must be evaluated carefully (it is safe in many places, but not always)

For that exact reason, before accepting this PR I double checked every change that @LukasReschke did, and all were correct :wink:

**Pull request merged**
