### PR TITLE
Test comparer

### PR DESCRIPTION
**Pull request by Remo**

### CODE REVIEW

**Comment by mlocati** [comment]
Is this meant to be merged?

**Comment by Remo** [comment]
I wanted to add more tests on my home computer and thus pushed it here.. Things are a bit chaotic, but I'll add more tests at some point

**Comment by mlocati** [comment]
Ok, I'll leave it untouched and under your control :wink:

**Comment by Remo** [comment]
@mlocati any idea how we can easily change the return value of `class_exists` (https://github.com/punic/punic/blob/master/code/Comparer.php#L41). I'd need that in order to test both cases.

I could add a variable, but that's super ugly just for testing. I could create some kind of mocking, but that would require quite a change.. Any great Michele like ideas on how to properly test this class?

**Comment by mlocati** [comment]
Well, I think that simply adding a setter could be enough... Something like this:

```php
public function setCollator($collator)
{
    $this->collator = $collator;
}
```

**Comment by Remo** [comment]
yes, but I'm not a big fan of modifying code for a single test.. I'll keep on thinking and if I can't find anything better I'll add a setter

**Comment by mlocati** [comment]
It's not such a big change, IMHO. Furthermore someone else may want to set their custom collator implementation...

**Comment by mlocati** [comment]
Can this be closed? Or are you willing to complete this PR?

**Pull request closed without merging**
