### PR TITLE
Switch to CLDR 34 + libphonenumber

### LINKED ISSUE #159: telephoneCodeData removed from CLDR 34
Follow up of https://github.com/punic/punic/issues/158#issuecomment-441018057

> I'd prefer copying the telephone data from CLDR 33 into future punic-data releases, rather than patching data from future CLDR releases back into to CLDR 33.

@c960657 I'd prefer to have an up-to-date reference data.
We simply need a list of territory code -> phone prefixes. Are you aware of such list that's reliable and up-to-date?

### PR DESCRIPTION
**Pull request by mlocati**
Fix #159, should also address #158

See also https://github.com/punic/data/pull/9

### CODE REVIEW

**Comment by c960657** [comment]
Sure :-)


The `internet` code mappings have been removed from CLDR (the commit message says “deprecate”, but it was moved completely):
https://unicode.org/cldr/trac/ticket/11072

I suggest we follow suit remove support for the `internet` type. We _could_ get the information elsewhere like the telephone data, but since this is a very recent feature addition, I think it is reasonable to just remove it.

Removing the six tests for this type fixes six tests in TerritoryTest.php.



The remaining test is fixed like this:
```
--- a/tests/Calendar/CalendarTest.php
+++ b/tests/Calendar/CalendarTest.php
@@ -1436,7 +1436,7 @@ class CalendarTest extends TestCase
             Calendar::getIntervalFormat('Gy', 'G')
         );
         $this->assertSame(
-            array('y G – y G', true),
+            array('y – y G', true),
             Calendar::getIntervalFormat('Gy', 'y')
         );
         $this->assertSame(
```

**Comment by mlocati** [comment]
I agree I'd remove the `internet` type.

About the change in the `getIntervalFormat` result: why the result changed?

**Comment by c960657** [comment]
It changed because the `Gy` skeleton got an explicit interval pattern:
```
<intervalFormatItem id="Gy">
  <greatestDifference id="G">y G – y G</greatestDifference>
  <greatestDifference id="y">y – y G</greatestDifference>
</intervalFormatItem>
```
Previously it fell back to the date format combined using the interval fallback pattern:
```
<dateFormatItem id="Gy">y G</dateFormatItem>
…
<intervalFormatFallback>{0} – {1}</intervalFormatFallback
```

But good point: With my first suggestion, the test no longer checks the fallback pattern. This is better:
```
diff --git a/tests/Calendar/CalendarTest.php b/tests/Calendar/CalendarTest.php
index e3b8472..75e1bab 100644
--- a/tests/Calendar/CalendarTest.php
+++ b/tests/Calendar/CalendarTest.php
@@ -1432,16 +1432,16 @@ class CalendarTest extends TestCase
             Calendar::getIntervalFormat('C', 's', 'de')
         );
         $this->assertSame(
-            array('y G – y G', true),
-            Calendar::getIntervalFormat('Gy', 'G')
+            array('QQQQ y – QQQQ y', true),
+            Calendar::getIntervalFormat('yQQQQ', 'y')
         );
         $this->assertSame(
-            array('y G – y G', true),
-            Calendar::getIntervalFormat('Gy', 'y')
+            array('QQQQ y – QQQQ y', true),
+            Calendar::getIntervalFormat('yQQQQ', 'Q')
         );
         $this->assertSame(
-            array('y G', null),
-            Calendar::getIntervalFormat('Gy', 'M')
+            array('QQQQ y', null),
+            Calendar::getIntervalFormat('yQQQQ', 'M')
         );
 
         // Combined date and time.
```

**Comment by mlocati** [comment]
You can submit a PR against the `cldr-34` branch of my fork https://github.com/mlocati/punic

**Pull request merged**
