### PR TITLE
replace is_null with null ==

### PR DESCRIPTION
**Pull request by Remo**
it's not something I want to merge, but I've noticed that `.. == null` is faster than `is_null`. Makes sense since it's just an operator and not a function call..

4 unit tests are failing though.. I also tried with `===` but that caused even more unit tests to fail.

The script mentioned here https://github.com/punic/punic/issues/32#issuecomment-70403783 is executed in about 8.4 seconds before and 7.3 seconds after this merge. Might be because of an error, will check this later.

(I'll replace them with `$var == null` if I'll actually want to merge this)

### CODE REVIEW

**Comment by mlocati** [comment]
Well, `is_null` should be the same as ` === null`. I'll inspect this

**Comment by Remo** [comment]
@mlocati I think I might have made a mistake, let's see what travis means to `===`

**Comment by mlocati** [comment]
It seems that isset may be even faster than `=== null`

**Comment by mlocati** [comment]
Let's see #68

**Comment by Remo** [comment]
it will work, my PR does the same, but yours is nicer as you swapped the order..

**Comment by mlocati** [comment]
Whoops, I didn't see your 2nd and 3rd commits here

**Pull request closed without merging**
