### PR TITLE
Use isset() instead of strlen()

### PR DESCRIPTION
**Pull request by LukasReschke**
isset() is way faster than counting the string length, furthermore counting a string's length is not really required unless you actually need the length somewhere.

### CODE REVIEW

**Comment by mlocati** [comment]
Do you have some benchmark of this? I always thought that strlen was as fast as [reading a structure value](https://github.com/php/php-src/blob/master/Zend/zend_builtin_functions.c#L521)...

**Comment by LukasReschke** [comment]
`isset()` has it's own Opcode which at least in ZendVM makes a considerable speed difference:

```php
<?php

session_write_close();
require_once('./3rdparty/punic/punic/punic.php');

$time1 = microtime(true);

$string = 'foo';
for ($i = 1; $i <= 10000000; $i++) {
	$bar = isset($string[0]);
}

$time2 = microtime(true);
echo 'isset time: ' . ($time2 - $time1);
echo '<br/>';

$time3 = microtime(true);

for ($i = 1; $i <= 10000000; $i++) {
	$bar = strlen($string);
}

$time4 = microtime(true);
echo 'strlen time: ' . ($time4 - $time3);
echo '<br/>';
```

isset time: 0.38738322257996
strlen time: 1.289724111557

**Comment by LukasReschke** [comment]
Isset:
```
Finding entry points
Branch analysis from position: 0
Return found
filename:       /in/QJIOA
function name:  (null)
number of ops:  4
compiled vars:  !0 = $string, !1 = $bar
line     # *  op                           fetch          ext  return  operands
---------------------------------------------------------------------------------
   3     0  >   ASSIGN                                                   !0, 'foo'
   4     1      ISSET_ISEMPTY_DIM_OBJ                       2000000  ~1      !0, 0
         2      ASSIGN                                                   !1, ~1
         3    > RETURN                                                   1
```

Strlen:
```
Finding entry points
Branch analysis from position: 0
Return found
filename:       /in/GC2ZS
function name:  (null)
number of ops:  5
compiled vars:  !0 = $string, !1 = $bar
line     # *  op                           fetch          ext  return  operands
---------------------------------------------------------------------------------
   3     0  >   ASSIGN                                                   !0, 'foo'
   4     1      SEND_VAR                                                 !0
         2      DO_FCALL                                      1  $1      'strlen'
         3      ASSIGN                                                   !1, $1
         4    > RETURN                                                   1
```

**Comment by mlocati** [comment]
Really interesting. Thanks!

**Comment by mlocati** [comment]
I just made a PR on your PR to fix some minor issues :wink:

**Comment by LukasReschke** [comment]
> I just made a PR on your PR to fix some minor issues :wink:

Merged. Thanks!

**Comment by mlocati** [comment]
Great!

**Comment by mlocati** [comment]
I run this script to evaluate the checks to see if strings are empty:
```php
@session_write_close();
foreach(
    array(
        'Test with empty string' => "",
        'Test with short string' => "short",
        'Test with long string' => str_repeat("This is a string that's quite long", 50),
    ) as $name => $string) {
    echo $name, "\n";

    $time1 = microtime(true);
    for ($i = 1; $i <= 10000000; $i++) {
        if(strcmp('', $string) !== 0) {
            ;
        }
    }
    $time2 = microtime(true);
    echo "\tstrcmp time: " . ($time2 - $time1), "\n";

    $time1 = microtime(true);
    for ($i = 1; $i <= 10000000; $i++) {
        if(strlen($string)) {
            ;
        }
    }
    $time2 = microtime(true);
    echo "\tstrlen time: " . ($time2 - $time1), "\n";


    $time1 = microtime(true);
    for ($i = 1; $i <= 10000000; $i++) {
        if($string != '') {
            ;
        }
    }
    $time2 = microtime(true);
    echo "\t!='' time  : " . ($time2 - $time1), "\n";

    $time1 = microtime(true);
    for ($i = 1; $i <= 10000000; $i++) {
        if($string !== '') {
            ;
        }
    }
    $time2 = microtime(true);
    echo "\t!=='' time : " . ($time2 - $time1), "\n";

    $time1 = microtime(true);
    for ($i = 1; $i <= 10000000; $i++) {
        if(isset($string[0])) {
            ;
        }
    }
    $time2 = microtime(true);
    echo "\tisset time : " . ($time2 - $time1), "\n";
}
```

And here's the  result:
```
Test with empty string
        strcmp time: 19.674000024796
        strlen time: 18.779000043869
        !='' time  : 1.2060000896454
        !=='' time : 1.1610000133514
        isset time : 1.1610000133514
Test with short string
        strcmp time: 19.750999927521
        strlen time: 18.803999900818
        !='' time  : 1.4279999732971
        !=='' time : 1.3760001659393
        isset time : 1.4089999198914
Test with long string
        strcmp time: 19.756000041962
        strlen time: 18.770999908447
        !='' time  : 1.4360001087189
        !=='' time : 1.385999917984
        isset time : 1.414999961853
```
`strcmp` and `strlen` are ways slower that `isset(..[0])`, but checking with ` !== ''` is even faster (and IMHO more readable).

**Comment by LukasReschke** [comment]
Indeed. Checking for empty strings would look nicer if done either via `!== ''` or `empty`

**Comment by mlocati** [comment]
I tend to avoid `empty` to check if a string is empty (`empty('0') == true` :worried: ).

**Pull request merged**
