### PR TITLE
Add Punic\Phone

### PR DESCRIPTION
**Pull request by mlocati**

### CODE REVIEW

**Comment by Remo** [comment]
looks good!

**Comment by Remo** [comment]
what's the reason for all the whitespace changes? PSR-2 requires white spaces there, doesn't it?

**Comment by mlocati** [comment]
> what's the reason for all the whitespace changes? PSR-2 requires white spaces there, doesn't it?

No spaces before and after dots: `A.B` instead of `A . B`... Or at least php-cs-fixer says so :wink:
I'm going to take a look at this.

**Comment by Remo** [comment]
I thought I've used php-cs-fixer too ;-)

**Comment by mlocati** [comment]
Latest versions includes the `concat_without_spaces` filter, but it's a symphony guideline and not a PSR guideline... So, what's next?

**Comment by Remo** [comment]
personally, I'd follow PSR as close as possible. I'm surprised symfony changed that..

**Comment by mlocati** [comment]
From http://symfony.com/doc/current/contributing/code/standards.html:
> Add a single space around binary operators (==, &&, ...), with the exception of the concatenation (.) operator;

**Comment by mlocati** [comment]
I'm going to close this PR and create a new one...

**Comment by Remo** [comment]
no, you'll kill my pull request on your pull request ;-)

**Comment by mlocati** [comment]
Ok, so let's keep this PR

**Comment by Remo** [comment]
that was just a joke, do whatever you want ;-)
I'm okay without the spaces, just looked a bit strange, not used to have it like that but maybe I followed PSR2 wrong..

**Comment by mlocati** [comment]
Ok, so let's push that big green button :wink:

**Comment by Remo** [comment]
:+1:

**Pull request merged**
